// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "IIDadata SUI",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "IIDadata SUI",
            targets: ["AppModule"],
            bundleIdentifier: "spm.swiftui.IIDadata-Tests.IntegrationTest",
            teamIdentifier: "UB936SP78M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calculator),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "IIDadata", package: "iidadata")
            ],
            path: "."
        )
    ]
)